## Задание 1.

Прочитать данные
`https://raw.githubusercontent.com/yakushinav/omo/main/data/movies.csv`

Имена столбцов
```
['color', 'director_name', 'num_critic_for_reviews', 'duration',
                'gross', 'movie_title', 'num_user_for_reviews', 'country',
                'cotent_rating', 'budget', 'title_year', 'imdb_score', 'genre']
```

In [9]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/yakushinav/omo/main/data/movies.csv',
                sep='|',
                header=None,
                na_values=['', '?', '-'],
                names=['color', 'director_name', 'num_critic_for_reviews', 'duration',
                'gross', 'movie_title', 'num_user_for_reviews', 'country',
                'cotent_rating', 'budget', 'title_year', 'imdb_score', 'genre'],
                thousands=',')

df.head()

,color,director_name,num_critic_for_reviews,duration,gross,movie_title,num_user_for_reviews,country,cotent_rating,budget,title_year,imdb_score,genre
0,Color,James Cameron,723.0,178.0,760505847.0,Avatar,3054.0,USA,PG-13,237000000.0,2009.0,7.9,Action
1,Color,Gore Verbinski,302.0,169.0,309404152.0,Pirates of the Caribbean: At World's End,1238.0,USA,PG-13,300000000.0,2007.0,7.1,Action
2,Color,Sam Mendes,602.0,148.0,200074175.0,Spectre,994.0,UK,PG-13,245000000.0,2015.0,6.8,Action
3,Color,Christopher Nolan,813.0,164.0,448130642.0,The Dark Knight Rises,2701.0,USA,PG-13,250000000.0,2012.0,8.5,Action
4,NaN,Doug Walker,NaN,NaN,NaN,Star Wars: Episode VII - The Force Awakens ...,NaN,NaN,NaN,NaN,NaN,7.1,Documentary

## Задание 2

Прочитать данные `https://raw.githubusercontent.com/yakushinav/omo/main/data/playstore.xlsx`.

Для столбца `Last_Updated` установить формат `дата_и_время`.

In [10]:
import pandas as pd
url = "https://raw.githubusercontent.com/yakushinav/omo/main/data/playstore.xlsx"
df = pd.read_excel(url)
df['Last_Updated'] = pd.to_datetime(df['Last_Updated'])

df.head()

,Unnamed: 0,App,Category,Rating,Installs,Type,Price,Content_ID,Genres,Last_Updated
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,"10,000+",Free,0,101,Art & Design,2018-01-07
1,1,Coloring book moana,ART_AND_DESIGN,3.9,"500,000+",Free,0,101,Art & Design;Pretend Play,2018-01-15
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,"5,000,000+",Free,0,101,Art & Design,2018-08-01
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,"50,000,000+",Free,0,102,Art & Design,2018-06-08
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,"100,000+",Free,0,101,Art & Design;Creativity,2018-06-20

## Задание 3

Прочитать данные `https://raw.githubusercontent.com/yakushinav/omo/main/data/artists.json`.

Выполнить сохранение в формат CSV. Прочитать полученный файл. Сравнить с исходным.

In [11]:
import pandas as pd
import json
import urllib

url = "https://raw.githubusercontent.com/yakushinav/omo/main/data/artists.json"
data = urllib.request.urlopen(url)

json_dict = json.load(data)

df_csv = pd.json_normalize(json_dict, record_path='bio', meta=['name', 'years', 'genre', 'nationality'])

df_csv

df_json = pd.read_json(url)

output_file = 'artists.csv'

df_json.to_csv(output_file, index=False)

if df_json.equals(df_csv):

    print("Сравнение исходных и загруженных данных: Cовпадают")

else:
    print("Сравнение исходных и загруженных данных: Не совпадают")

df_csv

Сравнение исходных и загруженных данных: Не совпадают

,full name,pronunciation,life span,info,wikipedia,paintings,name,years,genre,nationality
0,Amedeo Clemente Modigliani,[ameˈdɛːo modiʎˈʎaːni],12 July 1884 – 24 January 1920,was an Italian Jewish painter and sculptor who...,http://en.wikipedia.org/wiki/Amedeo_Modigliani,193,Amedeo Modigliani,1884 - 1920,Expressionism,Italian
1,Wassily Wassilyevich Kandinsky,"Васи́лий Васи́льевич Канди́нский, tr. Vasíliy ...",16 December [O.S. 4 December] 1866 – 13 Decemb...,was a Russian painter and art theorist.,http://en.wikipedia.org/wiki/Wassily_Kandinsky,88,Vasiliy Kandinskiy,1866 - 1944,"Expressionism,Abstractionism",Russian
2,Diego María de la Concepción Juan Nepomuceno E...,[ˈdjeɣo riˈβeɾa],"December 8, 1886 – November 24, 1957",was a prominent Mexican painter. His large fre...,http://en.wikipedia.org/wiki/Diego_Rivera,70,Diego Rivera,1886 - 1957,"Social Realism,Muralism",Mexican
3,Oscar-Claude Monet,[klod mɔnɛ],14 November 1840 – 5 December 1926,"was a French painter, a founder of French Impr...",http://en.wikipedia.org/wiki/Claude_Monet,73,Claude Monet,1840 - 1926,Impressionism,French
4,René François Ghislain Magritte,[ʁəne fʁɑ̃swa ɡilɛ̃ maɡʁit],21 November 1898 – 15 August 1967,Was a Belgian Surrealist artist. He became wel...,http://en.wikipedia.org/wiki/René_Magritte,194,Rene Magritte,1898 - 1967,"Surrealism,Impressionism",Belgian